import { describe, expect, it } from "vitest";
import { deriveBuyerProfile } from "../deriveBuyerProfile";
import { createEmptyAnswers, type BuyerAnswers } from "@/types/form";

const answers = (patch: Partial<BuyerAnswers> = {}): BuyerAnswers => ({
  ...createEmptyAnswers(), intent: "buy_property", buyer_status: "resident_indian", q4_value: "villa",
  budget: { min_inr: 1000000, max_inr: 2000000, not_sure: false, flexibility: "strict" },
  age_range: "30_40", purpose: "just_me", timeline: "within_3_months", ...patch,
});

describe("deriveBuyerProfile", () => {
  it("amplifies explicit nature and privacy priorities", () => { const p = deriveBuyerProfile(answers({ priorities: ["nature", "peace_and_quiet", "privacy"] })); expect(p.buyer_dna.nature).toBeGreaterThanOrEqual(75); expect(p.buyer_dna.privacy).toBeGreaterThanOrEqual(70); });
  it("keeps neither neutral and both moderate", () => { const base = deriveBuyerProfile(answers()); const neither = deriveBuyerProfile(answers({ visual: { pair1: "neither", pair2: "neither", pair3: "neither", pair4: "neither" } })); const both = deriveBuyerProfile(answers({ visual: { pair1: "both", pair2: "both", pair3: "both", pair4: "both" } })); expect(Object.entries(neither.visual_preferences).filter(([key]) => !["completed_pairs", "total_pairs"].includes(key)).every(([, value]) => value === 0)).toBe(true); expect(neither.derived_preferences.nature).toBe(base.derived_preferences.nature); expect(Object.entries(both.visual_preferences).filter(([key]) => !["completed_pairs", "total_pairs"].includes(key)).every(([, value]) => value === 0.55)).toBe(true); });
  it("uses visual choices in the derived profile", () => { const a = deriveBuyerProfile(answers({ visual: { pair1: "A", pair2: null, pair3: null, pair4: null } })); const b = deriveBuyerProfile(answers({ visual: { pair1: "B", pair2: null, pair3: null, pair4: null } })); expect(a.visual_preferences.mountain).toBe(1); expect(b.visual_preferences.modern).toBe(1); expect(a.derived_preferences.nature).not.toBe(b.derived_preferences.nature); });
  it("separates hard and soft constraints", () => { expect(deriveBuyerProfile(answers({ dealbreakers: [{ type: "noise", severity: "hard" }] })).constraints.hard_constraints).toContain("noise"); expect(deriveBuyerProfile(answers({ dealbreakers: [{ type: "noise", severity: "soft" }] })).constraints.soft_constraints).toContain("noise"); });
  it("uses investment purpose and ignores stale usage", () => { const p = deriveBuyerProfile(answers({ purpose: "investment_only", usage: "mostly_myself" })); expect(p.purchase_profile.investment_orientation).toBe("primary"); expect(p.derived_preferences.investment).toBeGreaterThanOrEqual(0.5); expect(p.explicit_inputs.usage).toBeNull(); expect(p.purchase_profile.usage).toBe("not_applicable"); });
  it("keeps an explicit property type strongest", () => { const p = deriveBuyerProfile(answers({ q4_value: "villa", priorities: ["nature", "privacy"] })); expect(p.property_preferences.villa).toBeGreaterThanOrEqual(Math.max(...Object.entries(p.property_preferences).filter(([key]) => key !== "villa").map(([, value]) => value))); });
  it("does not fabricate unknown budget amounts", () => { const p = deriveBuyerProfile(answers({ budget: { min_inr: null, max_inr: null, not_sure: true, flexibility: "very_flexible" } })); expect(p.explicit_inputs.budget.min_inr).toBeNull(); expect(p.explicit_inputs.budget.max_inr).toBeNull(); });
  it("does not retain an incompatible property selection after intent reset", () => { const raw = answers({ intent: "buy_land", q4_value: null }); const p = deriveBuyerProfile(raw); expect(p.property_preferences).not.toHaveProperty("villa"); expect(Object.keys(p.property_preferences)).toContain("residential_plot"); });
  it("puts each constraint in only its matching severity collection", () => { const hard = deriveBuyerProfile(answers({ dealbreakers: [{ type: "noise", severity: "hard" }] })).constraints; const soft = deriveBuyerProfile(answers({ dealbreakers: [{ type: "noise", severity: "soft" }] })).constraints; expect(hard.soft_constraints).not.toContain("noise"); expect(soft.hard_constraints).not.toContain("noise"); });
  it("keeps visual neither from reducing baseline-eligible axes", () => { const base = deriveBuyerProfile(answers()); const neither = deriveBuyerProfile(answers({ visual: { pair1: "neither", pair2: "neither", pair3: "neither", pair4: "neither" } })); expect(neither.derived_preferences.urban_access).toBe(base.derived_preferences.urban_access); expect(neither.derived_preferences.community).toBe(base.derived_preferences.community); });
  it("keeps baseline scores and family community moderate", () => { const p = deriveBuyerProfile(answers()); expect(p.derived_preferences.urban_access).toBe(0.5); expect(p.derived_preferences.maintenance_sensitivity).toBe(0.5); expect(p.derived_preferences.community).toBe(0.5); expect(p.derived_preferences.investment).toBe(0.18); expect(deriveBuyerProfile(answers({ purpose: "family_children" })).derived_preferences.community).toBeLessThanOrEqual(0.6); });
  it("is deterministic and preserves unknown budgets", () => { const raw = answers({ budget: { min_inr: null, max_inr: null, not_sure: true, flexibility: "very_flexible" } }); expect(JSON.stringify(deriveBuyerProfile(raw))).toBe(JSON.stringify(deriveBuyerProfile(raw))); expect(deriveBuyerProfile(raw).purchase_profile.budget_certainty).toBe("unknown"); });
});
